<?php
// finance/finance_request_pdf.php - Generate PDF for a finance request
// Uses browser-based PDF printing (no external libraries required)
require_once '../includes/auth.php';
requireLogin();
requireRole(['finance', 'admin']);

$conn = getDbConnection();
$request_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$stmt = $conn->prepare("SELECT r.*, l.full_name, l.email, l.position, l.department, l.nrc FROM lecturer_finance_requests r JOIN lecturers l ON r.lecturer_id = l.lecturer_id WHERE r.request_id = ?");
$stmt->bind_param("i", $request_id);
$stmt->execute();
$req = $stmt->get_result()->fetch_assoc();
if (!$req) die('Request not found.');

// Get airtime rate from fee_settings (instead of hardcoded value)
$conn->query("ALTER TABLE fee_settings ADD COLUMN IF NOT EXISTS lecturer_airtime_rate DECIMAL(10,2) DEFAULT 15000.00");
$fee_rates = $conn->query("SELECT lecturer_airtime_rate FROM fee_settings LIMIT 1")->fetch_assoc();
$airtime_rate = (float)($fee_rates['lecturer_airtime_rate'] ?? 15000);

// University logo path
$logo = '../assets/img/Logo.png';

// HTML for PDF
$html = '';
$html .= '<div class="header"><img src="'.$logo.'" style="height:60px;vertical-align:middle;"> <span style="font-size:2em;font-weight:bold;vertical-align:middle;">Exploits University</span></div>';
$html .= '<h2 style="text-align:center;">Lecturer Finance Request</h2>';
$html .= '<table class="info-table" width="100%">';
$html .= '<tr><td><b>Name:</b></td><td>'.$req['full_name'].'</td><td><b>Lecturer ID:</b></td><td>'.$req['lecturer_id'].'</td></tr>';
$html .= '<tr><td><b>Email:</b></td><td>'.$req['email'].'</td><td><b>NRC:</b></td><td>'.$req['nrc'].'</td></tr>';
$html .= '<tr><td><b>Position:</b></td><td>'.$req['position'].'</td><td><b>Department:</b></td><td>'.$req['department'].'</td></tr>';
$html .= '<tr><td><b>Period:</b></td><td>'.date('F Y', mktime(0,0,0,$req['month'],1,$req['year'])).'</td><td><b>Date Submitted:</b></td><td>'.date('M d, Y', strtotime($req['request_date'])).'</td></tr>';
$html .= '</table>';
$html .= '<hr>';
$html .= '<table class="info-table" width="100%">';
$html .= '<tr><td><b>Modules:</b></td><td>'.$req['total_modules'].'</td><td><b>Students:</b></td><td>'.$req['total_students'].'</td></tr>';
$html .= '<tr><td><b>Assignments Marked:</b></td><td>'.$req['total_assignments_marked'].'</td><td><b>Content Uploaded:</b></td><td>'.$req['total_content_uploaded'].'</td></tr>';
$html .= '<tr><td><b>Total Hours:</b></td><td>'.$req['total_hours'].'</td><td><b>Hourly Rate:</b></td><td>K'.number_format($req['hourly_rate']).'</td></tr>';
$html .= '<tr><td><b>Airtime/Bundle Rate:</b></td><td>K'.number_format($airtime_rate).'</td><td><b>Total Amount:</b></td><td><b>K'.number_format($req['total_amount']).'</b></td></tr>';
$html .= '</table>';
$html .= '<hr>';
$html .= '<b>Additional Notes:</b><br>'.nl2br(htmlspecialchars($req['additional_notes'])).'<br><br>';
if ($req['signature_path'] && file_exists('../uploads/signatures/'.$req['signature_path'])) {
    $html .= '<b>Signature:</b><br><img src="../uploads/signatures/'.htmlspecialchars($req['signature_path']).'" style="height:80px;border:1px solid #888;">';
}
$html .= '<br><br><i>Generated by VLE System - '.date('Y-m-d H:i').'</i>';

// Output HTML with Print Functionality
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finance Request #<?= $request_id ?> - <?= htmlspecialchars($req['full_name']) ?></title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .print-controls { background: #1e3c72; color: white; padding: 15px 20px; margin: -20px -20px 20px; display: flex; justify-content: space-between; align-items: center; }
        .print-controls h4 { margin: 0; }
        .print-controls button, .print-controls a { background: white; color: #1e3c72; border: none; padding: 8px 16px; border-radius: 5px; cursor: pointer; font-weight: 600; text-decoration: none; margin-left: 10px; }
        .print-controls button:hover, .print-controls a:hover { background: #e0e7ff; }
        .report-container { background: white; max-width: 800px; margin: 0 auto; padding: 30px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { border-bottom: 2px solid #333; margin-bottom: 20px; padding-bottom: 10px; }
        .info-table td { padding: 4px 8px; }
        hr { border: 1px solid #ddd; margin: 15px 0; }
        
        @media print {
            body { background: white; padding: 0; }
            .print-controls { display: none !important; }
            .report-container { box-shadow: none; padding: 0; max-width: none; }
            @page { size: A4 portrait; margin: 15mm; }
        }
    </style>
</head>
<body>
    <div class="print-controls">
        <h4>💰 Finance Request #<?= $request_id ?></h4>
        <div>
            <button onclick="window.print()">🖨️ Print / Save PDF</button>
            <a href="javascript:void(0)" onclick="window.close(); return false;">✕ Close</a>
            <a href="finance_manage_requests.php">← Back to Claims</a>
        </div>
    </div>
    <div class="report-container">
        <?= $html ?>
    </div>
</body>
</html>
