<?php
/**
 * Student Exam Clearance Page
 * Students already in the system apply for examination clearance here.
 * Their details are pre-filled from the students table.
 * Requires an active invite token (generated by finance officer).
 */
require_once '../includes/auth.php';
require_once '../includes/exam_clearance_helpers.php';
requireLogin();
requireRole(['student', 'exam_clearance_student']);

$conn = getDbConnection();
$user = getCurrentUser();
$is_external_student = hasRole('exam_clearance_student');
$student_id = null;
$success = '';
$error = '';

if ($is_external_student) {
    // External exam clearance students: find their student_id from exam_clearance_students
    $ext_stmt = $conn->prepare("SELECT student_id FROM exam_clearance_students WHERE email = ? ORDER BY registered_at DESC LIMIT 1");
    $ext_stmt->bind_param("s", $user['email']);
    $ext_stmt->execute();
    $ext_result = $ext_stmt->get_result()->fetch_assoc();
    $student_id = $ext_result['student_id'] ?? null;
} else {
    $student_id = $_SESSION['vle_related_id'];
}

// Load student info from the main students table (for system students)
$student_info = null;
if (!$is_external_student && $student_id) {
    $stmt = $conn->prepare("SELECT s.*, d.department_name FROM students s LEFT JOIN departments d ON CAST(s.department AS UNSIGNED) = d.department_id WHERE s.student_id = ?");
    $stmt->bind_param("s", $student_id);
    $stmt->execute();
    $student_info = $stmt->get_result()->fetch_assoc();
} elseif ($is_external_student && $student_id) {
    // Load from exam_clearance_students as a pseudo student_info
    $ext2 = $conn->prepare("SELECT * FROM exam_clearance_students WHERE student_id = ? ORDER BY registered_at DESC LIMIT 1");
    $ext2->bind_param("s", $student_id);
    $ext2->execute();
    $ec_row = $ext2->get_result()->fetch_assoc();
    if ($ec_row) {
        $student_info = [
            'student_id' => $ec_row['student_id'],
            'full_name' => $ec_row['full_name'],
            'email' => $ec_row['email'],
            'phone' => $ec_row['phone'],
            'program' => $ec_row['program'],
            'program_type' => $ec_row['program_type'],
            'department' => $ec_row['department'],
            'department_name' => $ec_row['department'],
            'campus' => $ec_row['campus'],
            'year_of_study' => $ec_row['year_of_study'],
            'gender' => $ec_row['gender'] ?? '',
            'national_id' => $ec_row['national_id'] ?? '',
            'address' => $ec_row['address'] ?? '',
        ];
    }
}

if (!$student_info) {
    $error = 'Student record not found. Please contact the admin.';
}

// Get fee settings for invoicing
$fee_settings = null;
$fee_rs = $conn->query("SELECT * FROM fee_settings WHERE id = 1");
if ($fee_rs) $fee_settings = $fee_rs->fetch_assoc();

// Check for active invite tokens
$active_invites = [];
$inv_rs = $conn->query("SELECT * FROM exam_clearance_invites WHERE is_active = 1 AND (expires_at IS NULL OR expires_at > NOW()) AND (max_uses = 0 OR times_used < max_uses) ORDER BY created_at DESC");
if ($inv_rs) {
    while ($row = $inv_rs->fetch_assoc()) $active_invites[] = $row;
}

// Check if student already has a clearance application for the current period
$existing_clearance = null;
$check = $conn->prepare("SELECT * FROM exam_clearance_students WHERE student_id = ? ORDER BY registered_at DESC LIMIT 1");
$check->bind_param("s", $student_id);
$check->execute();
$existing_clearance = $check->get_result()->fetch_assoc();

// Determine step
$step = 'apply'; // apply, upload_proof, done
if ($existing_clearance) {
    if (in_array($existing_clearance['status'], ['proof_submitted', 'cleared', 'rejected'])) {
        $step = 'done';
    } elseif (in_array($existing_clearance['status'], ['invoiced', 'registered', 'proof_requested'])) {
        $step = 'upload_proof';
    }
}

// Handle POST actions
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $student_info) {
    
    // Apply for exam clearance
    if ($_POST['action'] === 'apply') {
        $selected_invite_id = (int)($_POST['invite_id'] ?? 0);
        
        // Validate invite
        $inv_stmt = $conn->prepare("SELECT * FROM exam_clearance_invites WHERE invite_id = ? AND is_active = 1 AND (expires_at IS NULL OR expires_at > NOW()) AND (max_uses = 0 OR times_used < max_uses)");
        $inv_stmt->bind_param("i", $selected_invite_id);
        $inv_stmt->execute();
        $invite = $inv_stmt->get_result()->fetch_assoc();
        
        if (!$invite) {
            $error = 'No valid exam clearance invite available. Please contact the Finance Office.';
        } elseif ($existing_clearance && !in_array($existing_clearance['status'], ['rejected'])) {
            $error = 'You already have an active exam clearance application.';
            $step = ($existing_clearance['status'] === 'proof_submitted' || $existing_clearance['status'] === 'cleared') ? 'done' : 'upload_proof';
        } else {
            // Calculate invoice amount
            $program_type = strtolower($student_info['program_type'] ?? 'degree');
            if (!in_array($program_type, ['degree', 'professional', 'masters', 'doctorate'])) $program_type = 'degree';
            
            $clearance_type = $invite['clearance_type'] ?? 'endsemester';
            $min_percent = (int)($invite['minimum_payment_percent'] ?? 100);
            
            $tuition_amount = 0;
            $registration_fee = 0;
            if ($fee_settings) {
                switch ($program_type) {
                    case 'masters':
                        $tuition_amount = (float)($fee_settings['tuition_masters'] ?? 1100000);
                        break;
                    case 'doctorate':
                        $tuition_amount = (float)($fee_settings['tuition_doctorate'] ?? 2200000);
                        break;
                    default:
                        $tuition_amount = (float)($fee_settings['tuition_degree'] ?? 500000);
                        break;
                }
                // Add registration fee
                $registration_fee = (float)($fee_settings['registration_fee'] ?? 39500);
            } else {
                $tuition_amount = $program_type === 'masters' ? 1100000 : ($program_type === 'doctorate' ? 2200000 : 500000);
                $registration_fee = 39500;
            }
            $invoiced_amount = $tuition_amount + $registration_fee;
            
            $token = $invite['invite_token'];
            $balance = $invoiced_amount;
            $dept_name = $student_info['department_name'] ?? $student_info['department'] ?? '';
            $program_name = $student_info['program'] ?? '';
            $yr = $student_info['year_of_registration'] ?? date('Y');
            
            $ins = $conn->prepare("INSERT INTO exam_clearance_students (student_id, full_name, email, phone, program, program_type, department, campus, year_of_study, gender, national_id, address, entry_type, semester, year_of_registration, invite_token, invoiced_amount, registration_fee, balance, clearance_type, status, is_system_student) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'invoiced', 1)");
            $yos = (int)($student_info['year_of_study'] ?? 1);
            $ins->bind_param("ssssssssisssssssddds",
                $student_id,
                $student_info['full_name'],
                $student_info['email'],
                $student_info['phone'],
                $program_name,
                $program_type,
                $dept_name,
                $student_info['campus'],
                $yos,
                $student_info['gender'],
                $student_info['national_id'],
                $student_info['address'],
                $student_info['entry_type'],
                $student_info['semester'],
                $yr,
                $token,
                $invoiced_amount,
                $registration_fee,
                $balance,
                $clearance_type
            );
            
            if ($ins->execute()) {
                $clearance_id = $conn->insert_id;
                $conn->query("UPDATE exam_clearance_invites SET times_used = times_used + 1 WHERE invite_id = " . (int)$invite['invite_id']);
                
                // Log activity
                logExamClearanceActivity($conn, $clearance_id, 'application_submitted', 'student', (int)$user['user_id'], $student_info['full_name'], "Applied for {$program_type} exam clearance. Invoiced MWK " . number_format($invoiced_amount, 2));
                
                // Email notifications
                notifyStudentApplicationSubmitted($conn, $student_info['email'], $student_info['full_name'], $student_id, $program_name, $invoiced_amount);
                notifyFinanceNewApplication($conn, $student_info['full_name'], $student_id, $program_type);
                
                // Reload
                $check2 = $conn->prepare("SELECT * FROM exam_clearance_students WHERE clearance_id = ?");
                $check2->bind_param("i", $clearance_id);
                $check2->execute();
                $existing_clearance = $check2->get_result()->fetch_assoc();
                
                $step = 'upload_proof';
                $success = 'Application submitted! You have been invoiced <strong>MWK ' . number_format($invoiced_amount, 2) . '</strong>. Please upload your proof of payment below.';
            } else {
                $error = 'Failed to submit application: ' . $conn->error;
            }
        }
    }
    
    // Upload proof of payment
    if ($_POST['action'] === 'upload_proof' && $existing_clearance) {
        $clearance_id = (int)$existing_clearance['clearance_id'];
        $amount = (float)$_POST['amount'];
        $payment_reference = trim($_POST['payment_reference'] ?? '');
        $payment_date = $_POST['payment_date'] ?? date('Y-m-d');
        $bank_name = trim($_POST['bank_name'] ?? '');
        $notes = trim($_POST['notes'] ?? '');
        
        if ($amount <= 0) {
            $error = 'Please enter a valid payment amount.';
        } else {
            $proof_file = null;
            if (isset($_FILES['proof_file']) && $_FILES['proof_file']['error'] === UPLOAD_ERR_OK) {
                $allowed_types = ['image/jpeg', 'image/png', 'application/pdf'];
                $max_size = 5 * 1024 * 1024;
                
                if (!in_array($_FILES['proof_file']['type'], $allowed_types)) {
                    $error = 'Invalid file type. Only JPG, PNG, and PDF are allowed.';
                } elseif ($_FILES['proof_file']['size'] > $max_size) {
                    $error = 'File too large. Maximum size is 5MB.';
                } else {
                    $upload_dir = '../uploads/exam_clearance_payments/';
                    if (!is_dir($upload_dir)) {
                        mkdir($upload_dir, 0755, true);
                    }
                    $ext = pathinfo($_FILES['proof_file']['name'], PATHINFO_EXTENSION);
                    $safe_student_id = str_replace(['/', '\\', ' '], '_', $student_id);
                    $proof_file = 'exam_clearance_' . $safe_student_id . '_' . time() . '.' . $ext;
                    
                    if (!move_uploaded_file($_FILES['proof_file']['tmp_name'], $upload_dir . $proof_file)) {
                        $error = 'Failed to upload file. Please try again.';
                        $proof_file = null;
                    }
                }
            } else {
                $error = 'Please upload proof of payment.';
            }
            
            if ($proof_file && !$error) {
                $stmt = $conn->prepare("INSERT INTO exam_clearance_payments (clearance_id, amount, payment_reference, payment_date, bank_name, proof_file, notes) VALUES (?, ?, ?, ?, ?, ?, ?)");
                $stmt->bind_param("idsssss", $clearance_id, $amount, $payment_reference, $payment_date, $bank_name, $proof_file, $notes);
                
                if ($stmt->execute()) {
                    $conn->query("UPDATE exam_clearance_students SET status = 'proof_submitted', proof_of_payment = '" . $conn->real_escape_string($proof_file) . "', payment_reference = '" . $conn->real_escape_string($payment_reference) . "', amount_claimed = $amount WHERE clearance_id = $clearance_id");
                    
                    // Log activity
                    logExamClearanceActivity($conn, $clearance_id, 'proof_submitted', 'student', (int)$user['user_id'], $student_info['full_name'], "Uploaded proof of payment. Amount: MWK " . number_format($amount, 2) . ". Reference: {$payment_reference}");
                    
                    // Email notifications
                    notifyStudentProofSubmitted($conn, $student_info['email'], $student_info['full_name'], $amount);
                    notifyFinanceProofSubmitted($conn, $student_info['full_name'], $student_id, $amount);
                    
                    $step = 'done';
                    $success = 'Your proof of payment has been submitted! The Finance Office will review and process your exam clearance.';
                    
                    // Reload
                    $check3 = $conn->prepare("SELECT * FROM exam_clearance_students WHERE clearance_id = ?");
                    $check3->bind_param("i", $clearance_id);
                    $check3->execute();
                    $existing_clearance = $check3->get_result()->fetch_assoc();
                } else {
                    $error = 'Failed to save payment. Please try again.';
                }
            }
        }
    }
    
    // Apply again (after rejection)
    if ($_POST['action'] === 'apply_again') {
        $existing_clearance = null;
        $step = 'apply';
    }
}

// Get university name
$university_name = "Eastern University of Malawi and the World";
$settings_query = $conn->query("SELECT * FROM university_settings LIMIT 1");
if ($settings_query && $settings_query->num_rows > 0) {
    $s = $settings_query->fetch_assoc();
    $university_name = $s['university_name'] ?? $university_name;
}

$page_title = 'Examination Clearance';
$breadcrumbs = [['title' => 'Dashboard', 'url' => 'dashboard.php'], ['title' => 'Examination Clearance']];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $page_title ?> - VLE Student</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="../assets/css/global-theme.css" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; }
        .clearance-hero { background: linear-gradient(135deg, #10b981, #059669); color: #fff; border-radius: 16px; padding: 2rem; margin-bottom: 1.5rem; }
        .invoice-box { background: #f8f9fa; border: 2px dashed #10b981; border-radius: 12px; padding: 1.25rem; margin: 1rem 0; text-align: center; }
        .invoice-amount { font-size: 2rem; font-weight: 700; color: #059669; }
        .status-card { border-radius: 12px; padding: 2rem; text-align: center; }
    </style>
</head>
<body>
<?php include 'header_nav.php'; ?>

<div class="container-fluid py-4">
    <!-- Hero Banner -->
    <div class="clearance-hero">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h3><i class="bi bi-patch-check me-2"></i>Examination Clearance</h3>
                <p class="mb-0 opacity-75">Apply for examination clearance by submitting your proof of payment. Your application will be reviewed by the Finance Office.</p>
            </div>
            <div class="col-md-4 text-end d-none d-md-block">
                <i class="bi bi-shield-check" style="font-size: 4rem; opacity: 0.3;"></i>
            </div>
        </div>
    </div>
    
    <?php if ($success): ?>
        <div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle me-2"></i><?= $success ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
    <?php endif; ?>
    <?php if ($error): ?>
        <div class="alert alert-danger alert-dismissible fade show"><i class="bi bi-exclamation-triangle me-2"></i><?= htmlspecialchars($error) ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
    <?php endif; ?>
    
    <div class="row">
        <!-- Student Info Card -->
        <div class="col-lg-4 mb-4">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-primary text-white">
                    <h6 class="mb-0"><i class="bi bi-person me-2"></i>Your Details</h6>
                </div>
                <div class="card-body">
                    <?php if ($student_info): ?>
                    <table class="table table-sm table-borderless mb-0">
                        <tr><td class="text-muted">Student ID</td><td><strong><?= htmlspecialchars($student_id) ?></strong></td></tr>
                        <tr><td class="text-muted">Name</td><td><strong><?= htmlspecialchars($student_info['full_name']) ?></strong></td></tr>
                        <tr><td class="text-muted">Email</td><td><?= htmlspecialchars($student_info['email'] ?: '—') ?></td></tr>
                        <tr><td class="text-muted">Program</td><td><?= htmlspecialchars($student_info['program'] ?: '—') ?></td></tr>
                        <tr><td class="text-muted">Department</td><td><?= htmlspecialchars($student_info['department_name'] ?? $student_info['department'] ?? '—') ?></td></tr>
                        <tr><td class="text-muted">Year</td><td>Year <?= (int)($student_info['year_of_study'] ?? 1) ?></td></tr>
                        <tr><td class="text-muted">Campus</td><td><?= htmlspecialchars($student_info['campus'] ?: '—') ?></td></tr>
                    </table>
                    <?php else: ?>
                    <p class="text-danger mb-0">Student record not found.</p>
                    <?php endif; ?>
                </div>
            </div>
            
            <?php if ($existing_clearance): ?>
            <!-- Application Status -->
            <div class="card shadow-sm border-0 mt-3">
                <div class="card-header bg-info text-white">
                    <h6 class="mb-0"><i class="bi bi-info-circle me-2"></i>Application Status</h6>
                </div>
                <div class="card-body text-center">
                    <?php
                    $sc = ['registered'=>'secondary','invoiced'=>'info','proof_submitted'=>'warning','proof_requested'=>'orange','cleared'=>'success','rejected'=>'danger'];
                    ?>
                    <span class="badge bg-<?= $sc[$existing_clearance['status']] ?? 'secondary' ?> fs-6 px-3 py-2"><?= ucfirst(str_replace('_', ' ', $existing_clearance['status'])) ?></span>
                    <br>
                    <span class="badge bg-<?= ($existing_clearance['clearance_type'] ?? 'endsemester') === 'midsemester' ? 'warning text-dark' : 'success' ?> mt-2"><?= ($existing_clearance['clearance_type'] ?? 'endsemester') === 'midsemester' ? 'Mid-Semester Clearance' : 'End-of-Semester Clearance' ?></span>
                    <p class="text-muted small mt-2 mb-0">Applied: <?= date('M j, Y H:i', strtotime($existing_clearance['registered_at'])) ?></p>
                    <?php if ($existing_clearance['certificate_number']): ?>
                        <p class="text-success fw-bold mt-2 mb-0"><i class="bi bi-award me-1"></i>Certificate: <?= htmlspecialchars($existing_clearance['certificate_number']) ?></p>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
        
        <!-- Main Content -->
        <div class="col-lg-8">
            <?php if ($step === 'apply'): ?>
            <!-- STEP 1: Apply for Clearance -->
            <div class="card shadow-sm border-0">
                <div class="card-header bg-success text-white">
                    <h5 class="mb-0"><i class="bi bi-1-circle-fill me-2"></i>Apply for Examination Clearance</h5>
                </div>
                <div class="card-body">
                    <?php if (empty($active_invites)): ?>
                        <div class="text-center py-4">
                            <i class="bi bi-hourglass-split text-warning" style="font-size: 3rem;"></i>
                            <h5 class="mt-3">No Active Exam Clearance Window</h5>
                            <p class="text-muted">There is currently no open examination clearance period. Please check back later or contact the Finance Office.</p>
                        </div>
                    <?php else: ?>
                        <p class="text-muted">Your details from the student portal will be used. Select an active clearance window and submit your application.</p>
                        
                        <?php
                        // Auto-match invite to student's program type
                        $student_program_type = strtolower($student_info['program_type'] ?? 'degree');
                        if (!in_array($student_program_type, ['degree', 'professional', 'masters', 'doctorate'])) $student_program_type = 'degree';
                        
                        // Find best matching invite (same program type first, then any)
                        $matched_invite = null;
                        foreach ($active_invites as $inv) {
                            if (strtolower($inv['program_type']) === $student_program_type) {
                                $matched_invite = $inv;
                                break;
                            }
                        }
                        ?>
                        
                        <?php if ($matched_invite): ?>
                        <!-- Auto-matched clearance window -->
                        <div class="alert alert-success">
                            <i class="bi bi-check-circle-fill me-2"></i>
                            <strong>Clearance window found for your program:</strong>
                            <?= htmlspecialchars($matched_invite['description'] ?: ucfirst($matched_invite['program_type']) . ' Exam Clearance') ?>
                            (<?= ucfirst($matched_invite['program_type']) ?>)
                            <?php if ($matched_invite['expires_at']): ?>
                                — Expires <?= date('M j, Y', strtotime($matched_invite['expires_at'])) ?>
                            <?php endif; ?>
                        </div>
                        
                        <form method="POST">
                            <input type="hidden" name="action" value="apply">
                            <input type="hidden" name="invite_id" value="<?= $matched_invite['invite_id'] ?>">
                            
                            <div class="alert alert-info small">
                                <i class="bi bi-info-circle me-2"></i>Your details (name, student ID, program, department) will be auto-filled from your student record. You will need to upload proof of <strong>Registration Fee</strong> and <strong>Tuition Fee</strong> payment after submission.
                            </div>
                        <?php else: ?>
                        <!-- No matching window — let student pick manually -->
                        <form method="POST">
                            <input type="hidden" name="action" value="apply">
                            
                            <div class="alert alert-warning small">
                                <i class="bi bi-exclamation-triangle me-2"></i>No clearance window matching your program type (<strong><?= ucfirst($student_program_type) ?></strong>) was found. Please select one below or contact the Finance Office.
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Select Clearance Window <span class="text-danger">*</span></label>
                                <select name="invite_id" class="form-select" required>
                                    <option value="">-- Select --</option>
                                    <?php foreach ($active_invites as $inv): ?>
                                        <option value="<?= $inv['invite_id'] ?>">
                                            <?= htmlspecialchars($inv['description'] ?: ucfirst($inv['program_type']) . ' Exam Clearance') ?>
                                            (<?= ucfirst($inv['program_type']) ?>)
                                            <?php if ($inv['expires_at']): ?> - Expires <?= date('M j, Y', strtotime($inv['expires_at'])) ?><?php endif; ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        <?php endif; ?>
                            
                            <button type="submit" class="btn btn-success btn-lg w-100" onclick="return confirm('Submit your exam clearance application?')">
                                <i class="bi bi-send me-2"></i>Submit Application
                            </button>
                        </form>
                    <?php endif; ?>
                </div>
            </div>
            
            <?php elseif ($step === 'upload_proof' && $existing_clearance): ?>
            <!-- STEP 2: Upload Proof -->
            <div class="card shadow-sm border-0">
                <div class="card-header bg-warning text-dark">
                    <h5 class="mb-0"><i class="bi bi-2-circle-fill me-2"></i>Upload Proof of Payment</h5>
                </div>
                <div class="card-body">
                        <?php if ($existing_clearance['status'] === 'proof_requested'): ?>
                    <div class="alert alert-warning">
                        <i class="bi bi-exclamation-triangle-fill me-2"></i>
                        <strong>The Finance Office has requested proof of payment.</strong>
                        <?php 
                        $prt = $existing_clearance['proof_request_type'] ?? 'both';
                        if ($prt === 'tuition'): ?>
                            <br><span class="badge bg-info mt-1">Tuition Fee Payment Proof Required</span>
                        <?php elseif ($prt === 'registration'): ?>
                            <br><span class="badge bg-info mt-1">Registration Fee Payment Proof Required</span>
                        <?php else: ?>
                            <br><span class="badge bg-info mt-1">Both Tuition & Registration Fee Proof Required</span>
                        <?php endif; ?>
                        <?php if (!empty($existing_clearance['required_amount'])): ?>
                            <br><span class="badge bg-danger mt-1">Required Amount: MWK <?= number_format($existing_clearance['required_amount'], 2) ?></span>
                        <?php endif; ?>
                        <?php if (!empty($existing_clearance['finance_notes'])): ?>
                            <br><small><?= htmlspecialchars($existing_clearance['finance_notes']) ?></small>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                    
                    <div class="invoice-box">
                        <p class="mb-1 text-muted">Your Invoice Amount (<?= ucfirst($existing_clearance['program_type']) ?>)</p>
                        <div class="invoice-amount">MWK <?= number_format($existing_clearance['invoiced_amount'], 2) ?></div>
                        <p class="mb-0 small text-muted"><?= htmlspecialchars($existing_clearance['full_name']) ?> (<?= htmlspecialchars($existing_clearance['student_id']) ?>)</p>
                        <?php if ($existing_clearance['balance'] > 0): ?>
                            <span class="badge bg-danger mt-2">Balance: MWK <?= number_format($existing_clearance['balance'], 2) ?></span>
                        <?php else: ?>
                            <span class="badge bg-success mt-2">Fully Paid</span>
                        <?php endif; ?>
                    </div>
                    
                    <form method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="action" value="upload_proof">
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-semibold">Amount Paid (MWK) <span class="text-danger">*</span></label>
                                <input type="number" name="amount" class="form-control" required min="1" step="0.01" placeholder="e.g. 500000">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-semibold">Payment Reference <span class="text-danger">*</span></label>
                                <input type="text" name="payment_reference" class="form-control" required placeholder="Transaction/Receipt No.">
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-semibold">Payment Date <span class="text-danger">*</span></label>
                                <input type="date" name="payment_date" class="form-control" required value="<?= date('Y-m-d') ?>">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label fw-semibold">Bank Name</label>
                                <input type="text" name="bank_name" class="form-control" placeholder="e.g. National Bank">
                            </div>
                        </div>
                        
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Proof of Payment <span class="text-danger">*</span></label>
                            <input type="file" name="proof_file" class="form-control" required accept=".jpg,.jpeg,.png,.pdf">
                            <small class="text-muted">Upload bank slip, receipt, or screenshot (JPG, PNG, PDF. Max 5MB)</small>
                        </div>
                        
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Notes (optional)</label>
                            <textarea name="notes" class="form-control" rows="2" placeholder="Any additional information..."></textarea>
                        </div>
                        
                        <button type="submit" class="btn btn-warning btn-lg w-100"><i class="bi bi-upload me-2"></i>Submit Proof of Payment</button>
                    </form>
                </div>
            </div>
            
            <?php elseif ($step === 'done' && $existing_clearance): ?>
            <!-- STEP 3: Status -->
            <div class="card shadow-sm border-0">
                <div class="card-body status-card">
                    <?php if ($existing_clearance['status'] === 'cleared'): ?>
                        <div class="text-success mb-3"><i class="bi bi-patch-check-fill" style="font-size: 4rem;"></i></div>
                        <h4 class="text-success">Examination Clearance Approved!</h4>
                        <p class="text-muted">Your examination clearance has been approved. You are cleared to sit for examinations.</p>
                        <?php if ($existing_clearance['certificate_number']): ?>
                            <div class="alert alert-success">Certificate No: <strong><?= htmlspecialchars($existing_clearance['certificate_number']) ?></strong></div>
                        <?php endif; ?>
                        <p class="text-muted small">Cleared on <?= date('M j, Y H:i', strtotime($existing_clearance['cleared_at'])) ?></p>
                        <a href="../finance/exam_clearance_certificate.php?id=<?= $existing_clearance['clearance_id'] ?>" class="btn btn-success mt-2">
                            <i class="bi bi-file-earmark-pdf me-2"></i>Download Certificate PDF
                        </a>
                    
                    <?php elseif ($existing_clearance['status'] === 'rejected'): ?>
                        <div class="text-danger mb-3"><i class="bi bi-x-circle-fill" style="font-size: 4rem;"></i></div>
                        <h4 class="text-danger">Application Rejected</h4>
                        <p class="text-muted">Your exam clearance application was rejected. Please contact the Finance Office for more information.</p>
                        <?php if ($existing_clearance['finance_notes']): ?>
                            <div class="alert alert-warning"><strong>Reason:</strong> <?= htmlspecialchars($existing_clearance['finance_notes']) ?></div>
                        <?php endif; ?>
                        <form method="POST" class="mt-3">
                            <input type="hidden" name="action" value="apply_again">
                            <button type="submit" class="btn btn-primary"><i class="bi bi-arrow-repeat me-2"></i>Apply Again</button>
                        </form>
                    
                    <?php else: ?>
                        <div class="text-warning mb-3"><i class="bi bi-hourglass-split" style="font-size: 4rem;"></i></div>
                        <h4>Proof Submitted - Under Review</h4>
                        <p class="text-muted">Your proof of payment has been submitted. The Finance Office will review and process your clearance. Check back later for updates.</p>
                        <div class="alert alert-info text-start">
                            <strong>Amount Claimed:</strong> MWK <?= number_format($existing_clearance['amount_claimed'], 2) ?><br>
                            <strong>Status:</strong> <span class="badge bg-warning text-dark">Pending Review</span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
