<?php
// admin/finance_request_pdf.php - Generate PDF for a finance request
require_once '../includes/auth.php';
requireLogin();
requireRole(['finance', 'admin']);
require_once '../vendor/autoload.php'; // mPDF or TCPDF should be installed via Composer

$conn = getDbConnection();
$request_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$stmt = $conn->prepare("SELECT r.*, l.full_name, l.email, l.position, l.department, l.nrc FROM lecturer_finance_requests r JOIN lecturers l ON r.lecturer_id = l.lecturer_id WHERE r.request_id = ?");
$stmt->bind_param("i", $request_id);
$stmt->execute();
$req = $stmt->get_result()->fetch_assoc();
if (!$req) die('Request not found.');

// University logo path
$logo = '../assets/img/Logo.png';

// HTML for PDF
$html = '<style>body{font-family:sans-serif;} .header{border-bottom:2px solid #333;margin-bottom:20px;} .info-table td{padding:4px 8px;}</style>';
$html .= '<div class="header"><img src="'.$logo.'" style="height:60px;vertical-align:middle;"> <span style="font-size:2em;font-weight:bold;vertical-align:middle;">Exploits University</span></div>';
$html .= '<h2 style="text-align:center;">Lecturer Finance Request</h2>';
$html .= '<table class="info-table" width="100%">';
$html .= '<tr><td><b>Name:</b></td><td>'.$req['full_name'].'</td><td><b>Lecturer ID:</b></td><td>'.$req['lecturer_id'].'</td></tr>';
$html .= '<tr><td><b>Email:</b></td><td>'.$req['email'].'</td><td><b>NRC:</b></td><td>'.$req['nrc'].'</td></tr>';
$html .= '<tr><td><b>Position:</b></td><td>'.$req['position'].'</td><td><b>Department:</b></td><td>'.$req['department'].'</td></tr>';
$html .= '<tr><td><b>Period:</b></td><td>'.date('F Y', mktime(0,0,0,$req['month'],1,$req['year'])).'</td><td><b>Date Submitted:</b></td><td>'.date('M d, Y', strtotime($req['request_date'])).'</td></tr>';
$html .= '</table>';
$html .= '<hr>';
$html .= '<table class="info-table" width="100%">';
$html .= '<tr><td><b>Modules:</b></td><td>'.$req['total_modules'].'</td><td><b>Students:</b></td><td>'.$req['total_students'].'</td></tr>';
$html .= '<tr><td><b>Assignments Marked:</b></td><td>'.$req['total_assignments_marked'].'</td><td><b>Content Uploaded:</b></td><td>'.$req['total_content_uploaded'].'</td></tr>';
$html .= '<tr><td><b>Total Hours:</b></td><td>'.$req['total_hours'].'</td><td><b>Hourly Rate:</b></td><td>K'.number_format($req['hourly_rate']).'</td></tr>';
$html .= '<tr><td><b>Airtime/Bundle Rate:</b></td><td>K15,000</td><td><b>Total Amount:</b></td><td><b>K'.number_format($req['total_amount']).'</b></td></tr>';
$html .= '</table>';
$html .= '<hr>';
$html .= '<b>Additional Notes:</b><br>'.nl2br(htmlspecialchars($req['additional_notes'])).'<br><br>';
if ($req['signature_path'] && file_exists('../uploads/signatures/'.$req['signature_path'])) {
    $html .= '<b>Signature:</b><br><img src="../uploads/signatures/'.htmlspecialchars($req['signature_path']).'" style="height:80px;border:1px solid #888;">';
}
$html .= '<br><br><i>Generated by VLE System - '.date('Y-m-d H:i').'</i>';

// Generate PDF
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html);
$mpdf->Output('Finance_Request_'.$req['request_id'].'.pdf', 'I');
exit;
