<?php
/**
 * Generate Examination Reports - PDF & CSV
 * NCHE Accreditation Compliant Report Generator
 * Supports multiple report types for examination officers/managers
 */
require_once '../includes/auth.php';
requireLogin();
requireRole(['staff', 'examination_manager', 'admin']);
require_once '../vendor/autoload.php';

$conn = getDbConnection();
$user = getCurrentUser();

// --- Get parameters ---
$report_type = $_GET['report_type'] ?? 'exam_results_summary';
$format = $_GET['format'] ?? 'pdf';
$exam_id = (int)($_GET['exam_id'] ?? 0);
$course_id = (int)($_GET['course_id'] ?? 0);
$department_id = (int)($_GET['department_id'] ?? 0);
$exam_type = $_GET['exam_type'] ?? '';

// Grade config
$grade_scale = [
    'A' => ['min' => 75, 'max' => 100, 'desc' => 'Distinction', 'gpa' => '4.0'],
    'B' => ['min' => 65, 'max' => 74,  'desc' => 'Credit',      'gpa' => '3.0'],
    'C' => ['min' => 50, 'max' => 64,  'desc' => 'Pass',        'gpa' => '2.0'],
    'D' => ['min' => 40, 'max' => 49,  'desc' => 'Supplementary','gpa' => '1.0'],
    'F' => ['min' => 0,  'max' => 39,  'desc' => 'Fail',        'gpa' => '0.0'],
];

// Logo
$logo_path = realpath('../assets/img/Logo.png');
$logo_base64 = '';
if ($logo_path && file_exists($logo_path)) {
    $logo_base64 = 'data:image/png;base64,' . base64_encode(file_get_contents($logo_path));
}

$today = date('F d, Y');
$generated_by = $user['display_name'] ?? 'System';
$report_ref = 'NCHE-' . strtoupper(substr(md5($report_type . date('YmdHis')), 0, 10));

// ================= COMMON STYLES =================
$css = '
<style>
    body { font-family: "Times New Roman", serif; color: #222; font-size: 10pt; }
    .header { text-align: center; border-bottom: 3px double #1a3a6e; padding-bottom: 12px; margin-bottom: 15px; }
    .header img { height: 60px; }
    .uni-name { font-size: 20pt; font-weight: bold; color: #1a3a6e; margin: 5px 0 2px; }
    .uni-motto { font-size: 8pt; color: #666; font-style: italic; }
    .report-title { font-size: 13pt; font-weight: bold; color: #1a3a6e; margin-top: 8px; text-transform: uppercase; letter-spacing: 2px; }
    .report-subtitle { font-size: 9pt; color: #555; }
    .nche-tag { background: #1a3a6e; color: white; padding: 2px 8px; border-radius: 10px; font-size: 7pt; }
    .data-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
    .data-table th { background: #1a3a6e; color: #fff; padding: 6px 5px; font-size: 8pt; text-align: left; border: 1px solid #1a3a6e; }
    .data-table td { padding: 4px 5px; font-size: 8pt; border: 1px solid #ccc; }
    .data-table tr:nth-child(even) { background: #f5f7fa; }
    .data-table .num { text-align: center; }
    .summary-box { background: #f0f4f8; border: 1px solid #c0c8d4; padding: 10px; margin: 10px 0; border-radius: 4px; }
    .section-title { font-size: 11pt; font-weight: bold; color: #1a3a6e; border-bottom: 2px solid #1a3a6e; padding-bottom: 3px; margin: 15px 0 8px; }
    .grade-a { color: #198754; font-weight: bold; }
    .grade-b { color: #0d6efd; font-weight: bold; }
    .grade-c { color: #6f42c1; font-weight: bold; }
    .grade-d { color: #fd7e14; font-weight: bold; }
    .grade-f { color: #dc3545; font-weight: bold; }
    .footer { text-align: center; font-size: 7pt; color: #888; border-top: 1px solid #ccc; padding-top: 8px; margin-top: 25px; }
    .pass-badge { color: #198754; font-weight: bold; }
    .fail-badge { color: #dc3545; font-weight: bold; }
    .highlight-good { background: #d4edda; }
    .highlight-warn { background: #fff3cd; }
    .highlight-bad { background: #f8d7da; }
    .signature-table td { padding: 5px 15px; vertical-align: bottom; }
    .meta-table td { padding: 2px 8px; font-size: 9pt; }
    .meta-table .label { color: #555; font-weight: bold; width: 140px; }
    .watermark { position: fixed; top: 45%; left: 20%; opacity: 0.03; font-size: 55pt; color: #1a3a6e; transform: rotate(-30deg); z-index: -1; }
</style>';

// ================= HEADER HTML =================
function reportHeader($logo_base64, $title, $subtitle = '') {
    return '
    <div class="header">
        ' . ($logo_base64 ? '<img src="' . $logo_base64 . '" alt="Logo">' : '') . '
        <div class="uni-name">EXPLOITS UNIVERSITY MALAWI</div>
        <div class="uni-motto">"Knowledge is Power - Education for Transformation"</div>
        <div style="font-size:8pt; color:#444;">P.O. Box 1234, Lilongwe, Malawi | www.exploitsonline.com</div>
        <div class="report-title">' . $title . '</div>
        ' . ($subtitle ? '<div class="report-subtitle">' . $subtitle . '</div>' : '') . '
        <div style="margin-top:4px;"><span class="nche-tag">NCHE ACCREDITATION REPORT</span></div>
    </div>';
}

function reportFooter($report_ref, $generated_by) {
    return '
    <div class="footer">
        This report is generated by Exploits University Virtual Learning Environment (VLE) for NCHE accreditation purposes.<br>
        Any unauthorized alterations render this document invalid. Verify at: vle.exploitsonline.com<br>
        Report Reference: ' . $report_ref . ' | Generated by: ' . htmlspecialchars($generated_by) . ' | Date: ' . date('Y-m-d H:i:s') . '
    </div>';
}

function reportMeta($fields) {
    $html = '<table class="meta-table" width="100%"><tr>';
    $i = 0;
    foreach ($fields as $label => $value) {
        if ($i > 0 && $i % 2 === 0) $html .= '</tr><tr>';
        $html .= '<td class="label">' . $label . ':</td><td>' . $value . '</td>';
        $i++;
    }
    $html .= '</tr></table><hr style="border: 1px solid #1a3a6e; margin: 8px 0;">';
    return $html;
}

function signatureBlock() {
    return '
    <table class="signature-table" width="100%">
        <tr>
            <td width="33%" style="text-align:center;">
                <br><br>___________________________<br>
                <small>Examination Officer</small>
            </td>
            <td width="34%" style="text-align:center;">
                <br><br>___________________________<br>
                <small>Head of Department</small>
            </td>
            <td width="33%" style="text-align:center;">
                <br><br>___________________________<br>
                <small>Registrar</small>
            </td>
        </tr>
    </table>';
}

// ================= BUILD REPORT BY TYPE =================

$html = $css;
$filename = 'NCHE_Report';

switch ($report_type) {

// ==========================================
// 1. EXAM RESULTS SUMMARY
// ==========================================
case 'exam_results_summary':
    $where = ["e.results_published = 1"];
    $params = []; $types = "";
    
    if ($exam_id) { $where[] = "e.exam_id = ?"; $params[] = $exam_id; $types .= "i"; }
    if ($course_id) { $where[] = "e.course_id = ?"; $params[] = $course_id; $types .= "i"; }
    if ($exam_type) { $where[] = "e.exam_type = ?"; $params[] = $exam_type; $types .= "s"; }
    
    $sql = "SELECT e.exam_id, e.exam_name, e.exam_code, e.exam_type, e.total_marks, e.passing_marks,
                   e.start_time,
                   c.course_name, c.course_code,
                   COUNT(er.result_id) as candidates,
                   SUM(CASE WHEN er.is_passed = 1 THEN 1 ELSE 0 END) as passed,
                   SUM(CASE WHEN er.is_passed = 0 THEN 1 ELSE 0 END) as failed,
                   ROUND(AVG(er.percentage), 1) as avg_pct,
                   ROUND(MAX(er.percentage), 1) as highest,
                   ROUND(MIN(er.percentage), 1) as lowest,
                   ROUND(STDDEV(er.percentage), 1) as std_dev,
                   SUM(CASE WHEN er.grade = 'A' THEN 1 ELSE 0 END) as ga,
                   SUM(CASE WHEN er.grade = 'B' THEN 1 ELSE 0 END) as gb,
                   SUM(CASE WHEN er.grade = 'C' THEN 1 ELSE 0 END) as gc,
                   SUM(CASE WHEN er.grade = 'D' THEN 1 ELSE 0 END) as gd,
                   SUM(CASE WHEN er.grade = 'F' THEN 1 ELSE 0 END) as gf
            FROM exams e
            LEFT JOIN vle_courses c ON e.course_id = c.course_id
            LEFT JOIN exam_results er ON e.exam_id = er.exam_id
            WHERE " . implode(" AND ", $where) . "
            GROUP BY e.exam_id
            ORDER BY e.start_time DESC";
    
    $stmt = $conn->prepare($sql);
    if ($types) $stmt->bind_param($types, ...$params);
    $stmt->execute();
    $data = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        outputCSV('Exam_Results_Summary', 
            ['Exam Code', 'Exam Name', 'Course', 'Type', 'Candidates', 'Passed', 'Failed', 'Pass Rate %', 'Mean %', 'Highest %', 'Lowest %', 'Std Dev', 'Grade A', 'Grade B', 'Grade C', 'Grade D', 'Grade F'],
            array_map(function($r) {
                $pr = $r['candidates'] > 0 ? round(($r['passed']/$r['candidates'])*100, 1) : 0;
                return [$r['exam_code'], $r['exam_name'], $r['course_code'].' - '.$r['course_name'], $r['exam_type'], $r['candidates'], $r['passed'], $r['failed'], $pr, $r['avg_pct'], $r['highest'], $r['lowest'], $r['std_dev'], $r['ga'], $r['gb'], $r['gc'], $r['gd'], $r['gf']];
            }, $data)
        );
        exit;
    }
    
    // Calculate totals
    $tot_cand = array_sum(array_column($data, 'candidates'));
    $tot_pass = array_sum(array_column($data, 'passed'));
    $inst_pr = $tot_cand > 0 ? round(($tot_pass/$tot_cand)*100, 1) : 0;
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Examination Results Summary Report', 'Academic Performance Analysis');
    $html .= reportMeta([
        'Report Date' => $today,
        'Academic Year' => date('Y') . '/' . (date('Y')+1),
        'Total Examinations' => count($data),
        'Total Candidates' => number_format($tot_cand),
        'Institution Pass Rate' => '<strong>' . $inst_pr . '%</strong>',
        'Generated By' => htmlspecialchars($generated_by),
    ]);
    
    $html .= '<div class="section-title">1. Examination Results Summary</div>';
    $html .= '<table class="data-table">
        <thead><tr>
            <th>#</th><th>Code</th><th>Examination / Course</th><th>Type</th>
            <th class="num">Sat</th><th class="num">Pass</th><th class="num">Fail</th>
            <th class="num">Pass %</th><th class="num">Mean</th><th class="num">High</th>
            <th class="num">Low</th><th class="num">SD</th>
            <th class="num">A</th><th class="num">B</th><th class="num">C</th><th class="num">D</th><th class="num">F</th>
        </tr></thead><tbody>';
    
    $type_labels = ['quiz'=>'Quiz','mid_term'=>'Mid-Term','final'=>'Final','assignment'=>'CA'];
    foreach ($data as $i => $r) {
        $pr = $r['candidates'] > 0 ? round(($r['passed']/$r['candidates'])*100,1) : 0;
        $pr_highlight = $pr >= 70 ? 'highlight-good' : ($pr >= 50 ? 'highlight-warn' : 'highlight-bad');
        $html .= '<tr>
            <td>'.($i+1).'</td>
            <td>'.htmlspecialchars($r['exam_code']).'</td>
            <td>'.htmlspecialchars($r['exam_name']).($r['course_name'] ? '<br><small>'.$r['course_code'].' - '.$r['course_name'].'</small>' : '').'</td>
            <td>'.($type_labels[$r['exam_type']] ?? $r['exam_type']).'</td>
            <td class="num">'.$r['candidates'].'</td>
            <td class="num pass-badge">'.$r['passed'].'</td>
            <td class="num fail-badge">'.$r['failed'].'</td>
            <td class="num '.$pr_highlight.'">'.$pr.'%</td>
            <td class="num">'.$r['avg_pct'].'%</td>
            <td class="num">'.$r['highest'].'%</td>
            <td class="num">'.$r['lowest'].'%</td>
            <td class="num">'.($r['std_dev'] ?? '-').'</td>
            <td class="num grade-a">'.$r['ga'].'</td>
            <td class="num grade-b">'.$r['gb'].'</td>
            <td class="num grade-c">'.$r['gc'].'</td>
            <td class="num grade-d">'.$r['gd'].'</td>
            <td class="num grade-f">'.$r['gf'].'</td>
        </tr>';
    }
    $html .= '</tbody></table>';
    
    // Grade scale reference
    $html .= '<div class="section-title">2. Grading Scale Reference</div>';
    $html .= '<table class="data-table"><tr><th>Grade</th><th>Range</th><th>Classification</th><th>GPA</th></tr>';
    foreach ($grade_scale as $g => $info) {
        $html .= '<tr><td class="grade-'.strtolower($g).'">'.$g.'</td><td>'.$info['min'].'-'.$info['max'].'%</td><td>'.$info['desc'].'</td><td>'.$info['gpa'].'</td></tr>';
    }
    $html .= '</table>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Exam_Results_Summary_' . date('Ymd');
    break;

// ==========================================
// 2. COURSE ANALYSIS
// ==========================================
case 'course_analysis':
    $where = ["e.results_published = 1"];
    $params = []; $types = "";
    if ($course_id) { $where[] = "e.course_id = ?"; $params[] = $course_id; $types .= "i"; }
    if ($department_id) { $where[] = "(c.department_id = ? OR c.department = (SELECT department_name FROM departments WHERE department_id = ?))"; $params[] = $department_id; $params[] = $department_id; $types .= "ii"; }
    
    $sql = "SELECT c.course_id, c.course_name, c.course_code,
                   COUNT(DISTINCT e.exam_id) as exam_count,
                   COUNT(er.result_id) as total_candidates,
                   SUM(CASE WHEN er.is_passed = 1 THEN 1 ELSE 0 END) as passed,
                   ROUND(AVG(er.percentage), 1) as avg_pct,
                   ROUND(MAX(er.percentage), 1) as highest,
                   ROUND(MIN(er.percentage), 1) as lowest,
                   ROUND(STDDEV(er.percentage), 1) as std_dev,
                   SUM(CASE WHEN er.grade = 'A' THEN 1 ELSE 0 END) as ga,
                   SUM(CASE WHEN er.grade = 'B' THEN 1 ELSE 0 END) as gb,
                   SUM(CASE WHEN er.grade = 'C' THEN 1 ELSE 0 END) as gc,
                   SUM(CASE WHEN er.grade = 'D' THEN 1 ELSE 0 END) as gd,
                   SUM(CASE WHEN er.grade = 'F' THEN 1 ELSE 0 END) as gf
            FROM vle_courses c
            JOIN exams e ON c.course_id = e.course_id
            LEFT JOIN exam_results er ON e.exam_id = er.exam_id
            WHERE " . implode(" AND ", $where) . "
            GROUP BY c.course_id
            ORDER BY c.course_name";
    
    $stmt = $conn->prepare($sql);
    if ($types) $stmt->bind_param($types, ...$params);
    $stmt->execute();
    $data = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        outputCSV('Course_Analysis', 
            ['Course Code', 'Course Name', 'Exams', 'Candidates', 'Passed', 'Failed', 'Pass Rate %', 'Mean %', 'Highest', 'Lowest', 'Std Dev', 'A', 'B', 'C', 'D', 'F'],
            array_map(function($r) {
                $f = $r['total_candidates'] - $r['passed'];
                $pr = $r['total_candidates'] > 0 ? round(($r['passed']/$r['total_candidates'])*100,1) : 0;
                return [$r['course_code'], $r['course_name'], $r['exam_count'], $r['total_candidates'], $r['passed'], $f, $pr, $r['avg_pct'], $r['highest'], $r['lowest'], $r['std_dev'], $r['ga'], $r['gb'], $r['gc'], $r['gd'], $r['gf']];
            }, $data)
        );
        exit;
    }
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Course Performance Analysis Report', 'NCHE Accreditation - Course-Level Assessment');
    $html .= reportMeta([
        'Report Date' => $today,
        'Courses Analyzed' => count($data),
        'Generated By' => htmlspecialchars($generated_by),
        'Reference' => $report_ref,
    ]);
    
    $html .= '<div class="section-title">Course Performance Summary</div>';
    $html .= '<table class="data-table">
        <thead><tr><th>#</th><th>Code</th><th>Course Name</th><th class="num">Exams</th><th class="num">Candidates</th><th class="num">Passed</th><th class="num">Failed</th><th class="num">Pass %</th><th class="num">Mean</th><th class="num">High</th><th class="num">Low</th><th class="num">SD</th></tr></thead><tbody>';
    
    foreach ($data as $i => $r) {
        $failed = $r['total_candidates'] - $r['passed'];
        $pr = $r['total_candidates'] > 0 ? round(($r['passed']/$r['total_candidates'])*100,1) : 0;
        $pr_h = $pr >= 70 ? 'highlight-good' : ($pr >= 50 ? 'highlight-warn' : 'highlight-bad');
        $html .= '<tr><td>'.($i+1).'</td><td>'.$r['course_code'].'</td><td>'.$r['course_name'].'</td><td class="num">'.$r['exam_count'].'</td><td class="num">'.$r['total_candidates'].'</td><td class="num pass-badge">'.$r['passed'].'</td><td class="num fail-badge">'.$failed.'</td><td class="num '.$pr_h.'">'.$pr.'%</td><td class="num">'.$r['avg_pct'].'%</td><td class="num">'.$r['highest'].'%</td><td class="num">'.$r['lowest'].'%</td><td class="num">'.($r['std_dev']??'-').'</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // Grade distribution per course
    $html .= '<div class="section-title">Grade Distribution by Course</div>';
    $html .= '<table class="data-table"><thead><tr><th>Course</th><th class="num">A</th><th class="num">B</th><th class="num">C</th><th class="num">D</th><th class="num">F</th><th class="num">Total</th></tr></thead><tbody>';
    foreach ($data as $r) {
        $tot = $r['ga']+$r['gb']+$r['gc']+$r['gd']+$r['gf'];
        $html .= '<tr><td>'.$r['course_code'].' - '.$r['course_name'].'</td><td class="num grade-a">'.$r['ga'].'</td><td class="num grade-b">'.$r['gb'].'</td><td class="num grade-c">'.$r['gc'].'</td><td class="num grade-d">'.$r['gd'].'</td><td class="num grade-f">'.$r['gf'].'</td><td class="num">'.$tot.'</td></tr>';
    }
    $html .= '</tbody></table>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Course_Analysis_' . date('Ymd');
    break;

// ==========================================
// 3. DEPARTMENT PERFORMANCE
// ==========================================
case 'department_performance':
    $sql = "SELECT d.department_id, d.department_name,
                   COUNT(DISTINCT e.exam_id) as total_exams,
                   COUNT(DISTINCT c.course_id) as total_courses,
                   COUNT(er.result_id) as total_candidates,
                   SUM(CASE WHEN er.is_passed = 1 THEN 1 ELSE 0 END) as passed,
                   ROUND(AVG(er.percentage), 1) as avg_pct,
                   ROUND(MAX(er.percentage), 1) as highest,
                   ROUND(MIN(er.percentage), 1) as lowest,
                   ROUND(STDDEV(er.percentage), 1) as std_dev,
                   SUM(CASE WHEN er.grade = 'A' THEN 1 ELSE 0 END) as ga,
                   SUM(CASE WHEN er.grade = 'B' THEN 1 ELSE 0 END) as gb,
                   SUM(CASE WHEN er.grade = 'C' THEN 1 ELSE 0 END) as gc,
                   SUM(CASE WHEN er.grade = 'D' THEN 1 ELSE 0 END) as gd,
                   SUM(CASE WHEN er.grade = 'F' THEN 1 ELSE 0 END) as gf
            FROM departments d
            LEFT JOIN vle_courses c ON (d.department_id = c.department_id OR d.department_name = c.department)
            LEFT JOIN exams e ON c.course_id = e.course_id AND e.results_published = 1
            LEFT JOIN exam_results er ON e.exam_id = er.exam_id
            GROUP BY d.department_id
            HAVING total_candidates > 0
            ORDER BY d.department_name";
    
    $data = $conn->query($sql)->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        outputCSV('Department_Performance', 
            ['Department', 'Courses', 'Exams', 'Candidates', 'Passed', 'Failed', 'Pass Rate %', 'Mean %', 'Highest', 'Lowest', 'A', 'B', 'C', 'D', 'F', 'NCHE Status'],
            array_map(function($r) {
                $f = $r['total_candidates']-$r['passed'];
                $pr = $r['total_candidates']>0?round(($r['passed']/$r['total_candidates'])*100,1):0;
                return [$r['department_name'],$r['total_courses'],$r['total_exams'],$r['total_candidates'],$r['passed'],$f,$pr,$r['avg_pct'],$r['highest'],$r['lowest'],$r['ga'],$r['gb'],$r['gc'],$r['gd'],$r['gf'],$pr>=70?'Compliant':'Needs Review'];
            }, $data)
        );
        exit;
    }
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Department Performance Report', 'NCHE Accreditation - Programme Quality Assessment');
    $html .= reportMeta([
        'Report Date' => $today,
        'Departments Analyzed' => count($data),
        'Generated By' => htmlspecialchars($generated_by),
        'Reference' => $report_ref,
    ]);
    
    $html .= '<div class="section-title">1. Department Performance Overview</div>';
    $html .= '<table class="data-table"><thead><tr><th>#</th><th>Department / Programme</th><th class="num">Courses</th><th class="num">Exams</th><th class="num">Candidates</th><th class="num">Passed</th><th class="num">Failed</th><th class="num">Pass Rate</th><th class="num">Mean</th><th class="num">NCHE Status</th></tr></thead><tbody>';
    
    foreach ($data as $i => $r) {
        $failed = $r['total_candidates']-$r['passed'];
        $pr = $r['total_candidates']>0?round(($r['passed']/$r['total_candidates'])*100,1):0;
        $nche = $pr >= 70 ? '<span class="pass-badge">Compliant</span>' : '<span class="fail-badge">Needs Review</span>';
        $pr_h = $pr >= 70 ? 'highlight-good' : ($pr >= 50 ? 'highlight-warn' : 'highlight-bad');
        $html .= '<tr><td>'.($i+1).'</td><td><strong>'.htmlspecialchars($r['department_name']).'</strong></td><td class="num">'.$r['total_courses'].'</td><td class="num">'.$r['total_exams'].'</td><td class="num">'.$r['total_candidates'].'</td><td class="num pass-badge">'.$r['passed'].'</td><td class="num fail-badge">'.$failed.'</td><td class="num '.$pr_h.'">'.$pr.'%</td><td class="num">'.$r['avg_pct'].'%</td><td class="num">'.$nche.'</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // Department grade distribution
    $html .= '<div class="section-title">2. Grade Distribution by Department</div>';
    $html .= '<table class="data-table"><thead><tr><th>Department</th><th class="num">A</th><th class="num">B</th><th class="num">C</th><th class="num">D</th><th class="num">F</th><th class="num">Total</th></tr></thead><tbody>';
    foreach ($data as $r) {
        $tot = $r['ga']+$r['gb']+$r['gc']+$r['gd']+$r['gf'];
        $html .= '<tr><td>'.htmlspecialchars($r['department_name']).'</td><td class="num grade-a">'.$r['ga'].'</td><td class="num grade-b">'.$r['gb'].'</td><td class="num grade-c">'.$r['gc'].'</td><td class="num grade-d">'.$r['gd'].'</td><td class="num grade-f">'.$r['gf'].'</td><td class="num">'.$tot.'</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // Compliance summary
    $total_depts = count($data);
    $compliant = count(array_filter($data, fn($r) => $r['total_candidates']>0 && ($r['passed']/$r['total_candidates'])*100 >= 70));
    $html .= '<div class="summary-box"><strong>NCHE Compliance Summary:</strong> '.$compliant.' of '.$total_depts.' departments meet the 70% minimum pass rate threshold. '.($total_depts-$compliant).' department(s) require intervention.</div>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Department_Performance_' . date('Ymd');
    break;

// ==========================================
// 4. GRADE DISTRIBUTION
// ==========================================
case 'grade_distribution':
    $where = ["e.results_published = 1"];
    $params = []; $types = "";
    if ($exam_id) { $where[] = "e.exam_id = ?"; $params[] = $exam_id; $types .= "i"; }
    if ($exam_type) { $where[] = "e.exam_type = ?"; $params[] = $exam_type; $types .= "s"; }
    
    $sql = "SELECT er.grade, COUNT(*) as cnt, 
                   ROUND(AVG(er.percentage),1) as avg_pct,
                   ROUND(MIN(er.percentage),1) as min_pct,
                   ROUND(MAX(er.percentage),1) as max_pct
            FROM exam_results er
            JOIN exams e ON er.exam_id = e.exam_id
            WHERE " . implode(" AND ", $where) . "
            GROUP BY er.grade
            ORDER BY FIELD(er.grade, 'A','B','C','D','F')";
    
    $stmt = $conn->prepare($sql);
    if ($types) $stmt->bind_param($types, ...$params);
    $stmt->execute();
    $data = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        outputCSV('Grade_Distribution', ['Grade','Count','Percentage of Total','Mean %','Min %','Max %'],
            array_map(function($r) use ($data) {
                $total = array_sum(array_column($data, 'cnt'));
                return [$r['grade'],$r['cnt'],round(($r['cnt']/$total)*100,1).'%',$r['avg_pct'],$r['min_pct'],$r['max_pct']];
            }, $data)
        );
        exit;
    }
    
    $total = array_sum(array_column($data, 'cnt'));
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Grade Distribution Analysis Report', 'NCHE Accreditation - Statistical Analysis');
    $html .= reportMeta([
        'Report Date' => $today,
        'Total Results Analyzed' => number_format($total),
        'Generated By' => htmlspecialchars($generated_by),
        'Reference' => $report_ref,
    ]);
    
    $html .= '<div class="section-title">1. Grade Distribution Summary</div>';
    $html .= '<table class="data-table"><thead><tr><th>Grade</th><th>Classification</th><th>Range</th><th class="num">Count</th><th class="num">% of Total</th><th class="num">Mean Score</th><th class="num">Min Score</th><th class="num">Max Score</th></tr></thead><tbody>';
    
    foreach (['A','B','C','D','F'] as $g) {
        $found = null;
        foreach ($data as $d) { if ($d['grade'] === $g) { $found = $d; break; } }
        $cnt = $found ? $found['cnt'] : 0;
        $pct = $total > 0 ? round(($cnt/$total)*100, 1) : 0;
        $html .= '<tr><td class="grade-'.strtolower($g).'"><strong>'.$g.'</strong></td><td>'.$grade_scale[$g]['desc'].'</td><td>'.$grade_scale[$g]['min'].'-'.$grade_scale[$g]['max'].'%</td><td class="num">'.$cnt.'</td><td class="num">'.$pct.'%</td><td class="num">'.($found?$found['avg_pct']:'-').'%</td><td class="num">'.($found?$found['min_pct']:'-').'%</td><td class="num">'.($found?$found['max_pct']:'-').'%</td></tr>';
    }
    $html .= '<tr style="background:#e9ecef;font-weight:bold;"><td colspan="3">Total</td><td class="num">'.$total.'</td><td class="num">100%</td><td colspan="3"></td></tr>';
    $html .= '</tbody></table>';
    
    // Visual bar chart as HTML
    $html .= '<div class="section-title">2. Visual Grade Distribution</div>';
    $html .= '<table width="100%" style="margin:10px 0;">';
    $grade_colors_hex = ['A'=>'#198754','B'=>'#0d6efd','C'=>'#6f42c1','D'=>'#fd7e14','F'=>'#dc3545'];
    foreach (['A','B','C','D','F'] as $g) {
        $found = null;
        foreach ($data as $d) { if ($d['grade'] === $g) { $found = $d; break; } }
        $cnt = $found ? $found['cnt'] : 0;
        $pct = $total > 0 ? round(($cnt/$total)*100, 1) : 0;
        $bar_width = min($pct * 3, 100); // Scale for visual
        $html .= '<tr><td width="60" style="font-weight:bold;color:'.$grade_colors_hex[$g].'">Grade '.$g.'</td><td><div style="background:'.$grade_colors_hex[$g].';height:18px;width:'.$bar_width.'%;border-radius:3px;display:inline-block;"></div> <small>'.$pct.'% ('.$cnt.')</small></td></tr>';
    }
    $html .= '</table>';
    
    // NCHE analysis note
    $pass_grades = 0;
    foreach ($data as $d) { if (in_array($d['grade'], ['A','B','C'])) $pass_grades += $d['cnt']; }
    $pass_pct = $total > 0 ? round(($pass_grades/$total)*100,1) : 0;
    $html .= '<div class="summary-box"><strong>NCHE Quality Indicator:</strong> '.$pass_pct.'% of candidates achieved passing grades (A, B, or C). '.($pass_pct >= 70 ? 'This meets the NCHE minimum quality threshold.' : 'This is below the NCHE recommended 70% threshold. Intervention recommended.').'</div>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Grade_Distribution_' . date('Ymd');
    break;

// ==========================================
// 5. CONSOLIDATED SEMESTER REPORT
// ==========================================
case 'consolidated_semester':
    // Institution-wide consolidated stats
    $inst = $conn->query("
        SELECT COUNT(DISTINCT e.exam_id) as total_exams,
               COUNT(DISTINCT e.course_id) as total_courses,
               COUNT(er.result_id) as total_entries,
               COUNT(DISTINCT er.student_id) as unique_students,
               SUM(CASE WHEN er.is_passed=1 THEN 1 ELSE 0 END) as passed,
               ROUND(AVG(er.percentage),1) as avg_pct,
               ROUND(MAX(er.percentage),1) as highest,
               ROUND(MIN(er.percentage),1) as lowest,
               ROUND(STDDEV(er.percentage),1) as std_dev
        FROM exams e
        LEFT JOIN exam_results er ON e.exam_id = er.exam_id
        WHERE e.results_published = 1
    ")->fetch_assoc();
    
    $inst_pr = $inst['total_entries']>0?round(($inst['passed']/$inst['total_entries'])*100,1):0;
    
    // Exam type breakdown
    $type_breakdown = $conn->query("
        SELECT e.exam_type, COUNT(DISTINCT e.exam_id) as exams, COUNT(er.result_id) as entries,
               SUM(CASE WHEN er.is_passed=1 THEN 1 ELSE 0 END) as passed,
               ROUND(AVG(er.percentage),1) as avg_pct
        FROM exams e LEFT JOIN exam_results er ON e.exam_id = er.exam_id
        WHERE e.results_published = 1
        GROUP BY e.exam_type
    ")->fetch_all(MYSQLI_ASSOC);
    
    // Grade distribution
    $grades = $conn->query("
        SELECT er.grade, COUNT(*) as cnt
        FROM exam_results er JOIN exams e ON er.exam_id = e.exam_id
        WHERE e.results_published = 1
        GROUP BY er.grade
    ")->fetch_all(MYSQLI_ASSOC);
    
    // Department breakdown
    $depts = $conn->query("
        SELECT d.department_name,
               COUNT(DISTINCT e.exam_id) as exams,
               COUNT(er.result_id) as entries,
               SUM(CASE WHEN er.is_passed=1 THEN 1 ELSE 0 END) as passed,
               ROUND(AVG(er.percentage),1) as avg_pct
        FROM departments d
        LEFT JOIN vle_courses c ON (d.department_id = c.department_id OR d.department_name = c.department)
        LEFT JOIN exams e ON c.course_id = e.course_id AND e.results_published = 1
        LEFT JOIN exam_results er ON e.exam_id = er.exam_id
        GROUP BY d.department_id HAVING entries > 0
        ORDER BY d.department_name
    ")->fetch_all(MYSQLI_ASSOC);
    
    // Top performing exams
    $top_exams = $conn->query("
        SELECT e.exam_code, e.exam_name, c.course_name,
               COUNT(er.result_id) as candidates,
               ROUND(AVG(er.percentage),1) as avg_pct,
               ROUND((SUM(CASE WHEN er.is_passed=1 THEN 1 ELSE 0 END)*100.0/COUNT(er.result_id)),1) as pass_rate
        FROM exams e
        LEFT JOIN vle_courses c ON e.course_id = c.course_id
        JOIN exam_results er ON e.exam_id = er.exam_id
        WHERE e.results_published = 1
        GROUP BY e.exam_id HAVING candidates >= 1
        ORDER BY pass_rate DESC LIMIT 5
    ")->fetch_all(MYSQLI_ASSOC);
    
    // Worst performing exams
    $worst_exams = $conn->query("
        SELECT e.exam_code, e.exam_name, c.course_name,
               COUNT(er.result_id) as candidates,
               ROUND(AVG(er.percentage),1) as avg_pct,
               ROUND((SUM(CASE WHEN er.is_passed=1 THEN 1 ELSE 0 END)*100.0/COUNT(er.result_id)),1) as pass_rate
        FROM exams e
        LEFT JOIN vle_courses c ON e.course_id = c.course_id
        JOIN exam_results er ON e.exam_id = er.exam_id
        WHERE e.results_published = 1
        GROUP BY e.exam_id HAVING candidates >= 1
        ORDER BY pass_rate ASC LIMIT 5
    ")->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="Consolidated_Semester_Report_'.date('Ymd').'.csv"');
        $out = fopen('php://output', 'w');
        fputcsv($out, ['EXPLOITS UNIVERSITY - CONSOLIDATED SEMESTER REPORT']);
        fputcsv($out, ['Generated: '.date('Y-m-d H:i:s')]);
        fputcsv($out, []);
        fputcsv($out, ['Key Metric', 'Value']);
        fputcsv($out, ['Total Exams', $inst['total_exams']]);
        fputcsv($out, ['Total Courses', $inst['total_courses']]);
        fputcsv($out, ['Unique Students', $inst['unique_students']]);
        fputcsv($out, ['Total Entries', $inst['total_entries']]);
        fputcsv($out, ['Passed', $inst['passed']]);
        fputcsv($out, ['Pass Rate', $inst_pr.'%']);
        fputcsv($out, ['Average Score', $inst['avg_pct'].'%']);
        fclose($out);
        exit;
    }
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Consolidated Semester Examination Report', 'NCHE Accreditation - Institutional Performance Review');
    $html .= reportMeta([
        'Report Date' => $today,
        'Academic Year' => date('Y').'/'.(date('Y')+1),
        'Total Examinations' => $inst['total_exams'],
        'Total Courses' => $inst['total_courses'],
        'Unique Students' => number_format($inst['unique_students']),
        'Generated By' => htmlspecialchars($generated_by),
    ]);
    
    // 1. Key Performance Indicators
    $html .= '<div class="section-title">1. Key Performance Indicators (KPIs)</div>';
    $html .= '<div class="summary-box">
        <table width="100%"><tr>
            <td width="25%" style="text-align:center;"><strong style="font-size:16pt;color:#1a3a6e;">'.$inst['total_entries'].'</strong><br><small>Result Entries</small></td>
            <td width="25%" style="text-align:center;"><strong style="font-size:16pt;color:#198754;">'.$inst_pr.'%</strong><br><small>Pass Rate</small></td>
            <td width="25%" style="text-align:center;"><strong style="font-size:16pt;color:#0d6efd;">'.$inst['avg_pct'].'%</strong><br><small>Mean Score</small></td>
            <td width="25%" style="text-align:center;"><strong style="font-size:16pt;color:#6f42c1;">'.$inst['std_dev'].'</strong><br><small>Std Deviation</small></td>
        </tr></table>
    </div>';
    
    // 2. Exam Type Breakdown
    $html .= '<div class="section-title">2. Performance by Examination Type</div>';
    $html .= '<table class="data-table"><thead><tr><th>Exam Type</th><th class="num">Exams</th><th class="num">Candidates</th><th class="num">Passed</th><th class="num">Failed</th><th class="num">Pass Rate</th><th class="num">Mean</th></tr></thead><tbody>';
    $type_labels = ['quiz'=>'Quiz','mid_term'=>'Mid-Term Examination','final'=>'Final Examination','assignment'=>'Continuous Assessment'];
    foreach ($type_breakdown as $tb) {
        $f = $tb['entries']-$tb['passed'];
        $pr = $tb['entries']>0?round(($tb['passed']/$tb['entries'])*100,1):0;
        $html .= '<tr><td>'.($type_labels[$tb['exam_type']]??ucfirst($tb['exam_type'])).'</td><td class="num">'.$tb['exams'].'</td><td class="num">'.$tb['entries'].'</td><td class="num pass-badge">'.$tb['passed'].'</td><td class="num fail-badge">'.$f.'</td><td class="num">'.$pr.'%</td><td class="num">'.$tb['avg_pct'].'%</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // 3. Grade Distribution
    $html .= '<div class="section-title">3. Institution-Wide Grade Distribution</div>';
    $total_g = array_sum(array_column($grades, 'cnt'));
    $html .= '<table class="data-table"><thead><tr><th>Grade</th><th>Classification</th><th class="num">Count</th><th class="num">Percentage</th></tr></thead><tbody>';
    foreach (['A','B','C','D','F'] as $g) {
        $cnt = 0;
        foreach ($grades as $gd) if ($gd['grade']===$g) $cnt = $gd['cnt'];
        $pct = $total_g>0?round(($cnt/$total_g)*100,1):0;
        $html .= '<tr><td class="grade-'.strtolower($g).'">'.$g.'</td><td>'.$grade_scale[$g]['desc'].'</td><td class="num">'.$cnt.'</td><td class="num">'.$pct.'%</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // 4. Department Performance
    $html .= '<div class="section-title">4. Departmental Performance</div>';
    $html .= '<table class="data-table"><thead><tr><th>#</th><th>Department</th><th class="num">Exams</th><th class="num">Candidates</th><th class="num">Passed</th><th class="num">Pass Rate</th><th class="num">Mean</th><th class="num">NCHE</th></tr></thead><tbody>';
    foreach ($depts as $i => $d) {
        $pr = $d['entries']>0?round(($d['passed']/$d['entries'])*100,1):0;
        $nche = $pr>=70?'<span class="pass-badge">&#10003;</span>':'<span class="fail-badge">&#10007;</span>';
        $html .= '<tr><td>'.($i+1).'</td><td>'.htmlspecialchars($d['department_name']).'</td><td class="num">'.$d['exams'].'</td><td class="num">'.$d['entries'].'</td><td class="num">'.$d['passed'].'</td><td class="num">'.$pr.'%</td><td class="num">'.$d['avg_pct'].'%</td><td class="num">'.$nche.'</td></tr>';
    }
    $html .= '</tbody></table>';
    
    // 5. Top & Bottom Performing Exams
    $html .= '<div class="section-title">5. Performance Extremes</div>';
    $html .= '<table width="100%"><tr><td width="48%" style="vertical-align:top;">';
    $html .= '<strong style="color:#198754;">Top Performing Examinations</strong>';
    $html .= '<table class="data-table"><thead><tr><th>Exam</th><th class="num">Candidates</th><th class="num">Pass Rate</th><th class="num">Mean</th></tr></thead><tbody>';
    foreach ($top_exams as $te) {
        $html .= '<tr><td>'.htmlspecialchars($te['exam_code'].' - '.$te['exam_name']).'</td><td class="num">'.$te['candidates'].'</td><td class="num pass-badge">'.$te['pass_rate'].'%</td><td class="num">'.$te['avg_pct'].'%</td></tr>';
    }
    $html .= '</tbody></table></td><td width="4%"></td><td width="48%" style="vertical-align:top;">';
    $html .= '<strong style="color:#dc3545;">Examinations Requiring Attention</strong>';
    $html .= '<table class="data-table"><thead><tr><th>Exam</th><th class="num">Candidates</th><th class="num">Pass Rate</th><th class="num">Mean</th></tr></thead><tbody>';
    foreach ($worst_exams as $we) {
        $html .= '<tr><td>'.htmlspecialchars($we['exam_code'].' - '.$we['exam_name']).'</td><td class="num">'.$we['candidates'].'</td><td class="num fail-badge">'.$we['pass_rate'].'%</td><td class="num">'.$we['avg_pct'].'%</td></tr>';
    }
    $html .= '</tbody></table></td></tr></table>';
    
    // Compliance summary
    $compliant_d = 0;
    foreach ($depts as $d) { if ($d['entries']>0 && ($d['passed']/$d['entries'])*100 >= 70) $compliant_d++; }
    $html .= '<div class="summary-box">
        <strong>NCHE Institutional Compliance Summary</strong><br>
        - Institution Pass Rate: <strong>'.$inst_pr.'%</strong> '.($inst_pr>=70?'(Meets NCHE threshold)':'(Below NCHE threshold)').'<br>
        - Compliant Departments: '.$compliant_d.' / '.count($depts).'<br>
        - Mean Score: '.$inst['avg_pct'].'% | Highest: '.$inst['highest'].'% | Lowest: '.$inst['lowest'].'%<br>
        - Standard Deviation: '.$inst['std_dev'].' (Lower indicates more consistent performance)
    </div>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Consolidated_Semester_Report_' . date('Ymd');
    break;

// ==========================================
// 6. STUDENT RESULTS LIST (Per Exam)
// ==========================================
case 'student_list':
    if (!$exam_id) die('Please select a specific examination.');
    
    // Get exam details
    $stmt = $conn->prepare("SELECT e.*, c.course_name, c.course_code, l.full_name as lecturer_name 
                            FROM exams e LEFT JOIN vle_courses c ON e.course_id = c.course_id
                            LEFT JOIN lecturers l ON e.lecturer_id = l.lecturer_id
                            WHERE e.exam_id = ?");
    $stmt->bind_param("i", $exam_id);
    $stmt->execute();
    $exam = $stmt->get_result()->fetch_assoc();
    if (!$exam) die('Examination not found.');
    
    // Get all results for this exam
    $stmt = $conn->prepare("
        SELECT er.*, s.full_name, s.student_id as sid, s.department, s.year_of_study,
               es.started_at, es.ended_at,
               (SELECT COUNT(*) FROM exam_monitoring em WHERE em.session_id = er.session_id AND em.event_type IN ('tab_switch','window_blur','face_not_detected','multiple_faces')) as violations
        FROM exam_results er
        JOIN students s ON er.student_id = s.student_id
        LEFT JOIN exam_sessions es ON er.session_id = es.session_id
        WHERE er.exam_id = ?
        ORDER BY s.full_name
    ");
    $stmt->bind_param("i", $exam_id);
    $stmt->execute();
    $data = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    
    if ($format === 'csv') {
        outputCSV('Student_Results_'.$exam['exam_code'], 
            ['#', 'Student ID', 'Student Name', 'Department', 'Year', 'Score', 'Out Of', 'Percentage', 'Grade', 'Status', 'Violations', 'Date'],
            array_map(function($r, $i) use ($exam) {
                return [($i+1), $r['sid'], $r['full_name'], $r['department'], $r['year_of_study'], $r['score'], $exam['total_marks'], $r['percentage'].'%', $r['grade'], $r['is_passed']?'Pass':'Fail', $r['violations'], $r['submitted_at']];
            }, $data, array_keys($data))
        );
        exit;
    }
    
    // Calculate stats
    $total_c = count($data);
    $passed = count(array_filter($data, fn($r)=>$r['is_passed']));
    $avg = $total_c>0?round(array_sum(array_column($data,'percentage'))/$total_c,1):0;
    $pr = $total_c>0?round(($passed/$total_c)*100,1):0;
    
    $html .= '<div class="watermark">EXPLOITS UNIVERSITY</div>';
    $html .= reportHeader($logo_base64, 'Student Results List', htmlspecialchars($exam['exam_name']));
    $html .= reportMeta([
        'Examination' => htmlspecialchars($exam['exam_code'].' - '.$exam['exam_name']),
        'Course' => htmlspecialchars(($exam['course_code']??'').' - '.($exam['course_name']??'N/A')),
        'Type' => ucfirst(str_replace('_',' ',$exam['exam_type'])),
        'Total Marks' => $exam['total_marks'].' (Pass: '.$exam['passing_marks'].')',
        'Lecturer' => htmlspecialchars($exam['lecturer_name']??'N/A'),
        'Exam Date' => $exam['start_time'] ? date('d M Y', strtotime($exam['start_time'])) : 'N/A',
        'Candidates' => $total_c,
        'Pass Rate' => '<strong>'.$pr.'%</strong>',
    ]);
    
    // Summary box
    $html .= '<div class="summary-box">
        <table width="100%"><tr>
            <td width="20%"><strong>Candidates:</strong> '.$total_c.'</td>
            <td width="20%"><strong class="pass-badge">Passed:</strong> '.$passed.'</td>
            <td width="20%"><strong class="fail-badge">Failed:</strong> '.($total_c-$passed).'</td>
            <td width="20%"><strong>Mean:</strong> '.$avg.'%</td>
            <td width="20%"><strong>Pass Rate:</strong> '.$pr.'%</td>
        </tr></table>
    </div>';
    
    // Student list table
    $html .= '<table class="data-table"><thead><tr>
        <th>#</th><th>Student ID</th><th>Student Name</th><th>Department</th><th>Year</th>
        <th class="num">Score</th><th class="num">%</th><th class="num">Grade</th><th>Status</th><th class="num">Violations</th>
    </tr></thead><tbody>';
    
    foreach ($data as $i => $r) {
        $status = $r['is_passed'] ? '<span class="pass-badge">Pass</span>' : '<span class="fail-badge">Fail</span>';
        $v_class = $r['violations'] > 0 ? 'fail-badge' : '';
        $html .= '<tr>
            <td>'.($i+1).'</td>
            <td>'.$r['sid'].'</td>
            <td>'.htmlspecialchars($r['full_name']).'</td>
            <td>'.htmlspecialchars($r['department']??'').'</td>
            <td class="num">'.$r['year_of_study'].'</td>
            <td class="num">'.number_format($r['score'],1).' / '.$exam['total_marks'].'</td>
            <td class="num">'.number_format($r['percentage'],1).'%</td>
            <td class="num grade-'.strtolower($r['grade']).'">'.$r['grade'].'</td>
            <td>'.$status.'</td>
            <td class="num '.$v_class.'">'.$r['violations'].'</td>
        </tr>';
    }
    $html .= '</tbody></table>';
    
    // Grade distribution for this exam
    $html .= '<div class="section-title">Grade Distribution</div>';
    $html .= '<table class="data-table"><thead><tr><th>Grade</th><th>Classification</th><th class="num">Count</th><th class="num">Percentage</th></tr></thead><tbody>';
    $grade_counts = array_count_values(array_column($data, 'grade'));
    foreach (['A','B','C','D','F'] as $g) {
        $cnt = $grade_counts[$g] ?? 0;
        $pct = $total_c>0?round(($cnt/$total_c)*100,1):0;
        $html .= '<tr><td class="grade-'.strtolower($g).'">'.$g.'</td><td>'.$grade_scale[$g]['desc'].'</td><td class="num">'.$cnt.'</td><td class="num">'.$pct.'%</td></tr>';
    }
    $html .= '</tbody></table>';
    
    $html .= signatureBlock();
    $html .= reportFooter($report_ref, $generated_by);
    $filename = 'Student_Results_' . $exam['exam_code'] . '_' . date('Ymd');
    break;

default:
    die('Invalid report type.');
}

// ================= OUTPUT PDF =================
try {
    $mpdf = new \Mpdf\Mpdf([
        'margin_top' => 12,
        'margin_bottom' => 12,
        'margin_left' => 12,
        'margin_right' => 12,
        'format' => 'A4-L', // Landscape for more columns
    ]);
    
    // Use portrait for student list and grade distribution
    if (in_array($report_type, ['student_list', 'grade_distribution'])) {
        $mpdf = new \Mpdf\Mpdf([
            'margin_top' => 12,
            'margin_bottom' => 12,
            'margin_left' => 15,
            'margin_right' => 15,
            'format' => 'A4',
        ]);
    }
    
    $mpdf->SetTitle('NCHE Report - ' . $report_type);
    $mpdf->SetAuthor('Exploits University VLE');
    $mpdf->SetCreator('VLE Examination System');
    $mpdf->SetProtection(['print', 'copy'], '', 'admin_nche_eu2026');
    
    $mpdf->WriteHTML($html);
    $mpdf->Output($filename . '.pdf', 'I');
} catch (Exception $e) {
    die('PDF generation error: ' . $e->getMessage());
}

// ================= CSV HELPER =================
function outputCSV($filename, $headers, $rows) {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '_' . date('Ymd') . '.csv"');
    $out = fopen('php://output', 'w');
    fprintf($out, chr(0xEF) . chr(0xBB) . chr(0xBF)); // BOM for Excel
    fputcsv($out, $headers);
    foreach ($rows as $row) fputcsv($out, $row);
    fclose($out);
}
